api/urls.py
from django.urls import path
from .views import ItemListView


urlpatterns = [
    path('product-list/', ItemListView.as_view(), name='product-list'),
    # path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
]

base/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),

    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('paysuccess/', views.paysuccess, name='paysuccess'),
    path('payfail/', views.payfail, name='payfail'),
    path('about/', views.about, name='about'),
    
    # path('confirmation/', views.ConfirmationView.as_view(), name='confirmation'),
    path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove_from_cart'),
    path('add_to_cart/<slug>/', views.add_to_cart, name='add_to_cart'),
    path('contact/', views.contact, name='contact'),
    path('detail/<slug>/', views.DetailView.as_view(), name='detail'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('shop/', views.shop, name='shop'),
    path('hauts/', views.hauts, name='hauts'),
    path('robes/', views.robes, name='robes'),

    path('pantalon/', views.pantalon, name='pantalon'),
    path('jupes/', views.jupes, name='jupes'),

    path('update_profile/', views.update_profile, name='update_profile'),
    
 

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    # path('', include('users.urls')),
    path('accounts/', include('allauth.urls')),
  #  path('api-auth/', include('rest_framework.urls')),
 #   path('api/', include('api.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from pickle import FALSE, TRUE
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.db.models.signals import post_save
from django.dispatch import receiver

#une liste de liste
CATEGORY_CHOICES=(
    ('Rb', 'robe'),
    ('J', 'Jupe'),
    ('H', 'Haut'),
    ('C', 'Cargo'),
    ('Pt', 'Pantalon'),)

SIZE_CHOICES=(
    ('XS', 'extra petite'),
    ('S', 'petite'),
    ('M', 'moyenne'),
    ('L', 'large'),
    ('XL', 'extra large'),
    ('XL', 'très extra large'),
    )
LABEL_CHOICES=(
    ('NA', 'nouvel article'),
    ('SO', 'Vendu'),
)

PAYMENT_CHOICES = (
    ('FLOOZ', 'FLOOZ'),
    ('TMONEY', 'TMONEY'),
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    numero = models.IntegerField(null=True, blank=False)
    birth_date = models.DateField(null=True, blank=True)

    def get_user_number(self):
        return self.numero

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Item(models.Model):
    title = models.CharField(max_length=150)
    price = models.IntegerField()
    discount_price = models.IntegerField(blank=True, null=True)
    size=models.CharField(choices=SIZE_CHOICES, max_length=2,default="moyenne")
    slug = models.SlugField()
    category=models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    labels=models.CharField(choices=LABEL_CHOICES, max_length=2)
    description=models.TextField(blank=True, null=True)
    image = models.ImageField(default='default.jpg',upload_to='static/images')
    image2 = models.ImageField(default='default.jpg',upload_to='static/images')
    image3 = models.ImageField(default='default.jpg',upload_to='static/images')


    def __str__(self):
        return self.title
    
    # def get_change_label(self):
    #     return self.quantity * self.item.price
         
    def get_add_to_cart_url(self):
        return reverse('add_to_cart', kwargs={'slug':self.slug})

    def get_remove_from_cart_url(self):
        return reverse('remove_from_cart', kwargs={'slug':self.slug})


class Variation(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    class Meta:
        unique_together = (
            ('item', 'name')
        )

    def __str__(self):
        return self.name

class ItemVariation(models.Model):
    variation = models.ForeignKey(Variation, on_delete=models.CASCADE)
    value = models.CharField(max_length=200)
    attachment = models.ImageField(upload_to="static/images", blank=True, null=True)

    class Meta:
        unique_together = (
            ('variation', 'value')
        )

    def __str__(self):
        return self.value

class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price
    


    def get_total_item_discount_price(self):
            return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_final_price()


    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_item_discount_price()
        return self.get_total_item_price()

    
    
  
class Order(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    items=models.ManyToManyField(OrderItem)
    address= models.ForeignKey("Address", on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey("Payment", on_delete=models.SET_NULL, blank=True, null=True)
    ordered=models.BooleanField(default=False)
    start_date=models.DateTimeField(auto_now_add=True)
    ordered_date=models.DateTimeField()


    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        # if self.coupon:
        #     total -= self.coupon.amount
        return total
    

    def get_total_plus_shipping(self):
        return self.get_total() + 1000



class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=200)
    apartment_address = models.CharField(max_length=200)
    country = CountryField(multiple=False, default="TG")
    zip = models.CharField(max_length=200)
    save_info = models.BooleanField(default=False)
    default = models.BooleanField(default=False)
    use_default = models.BooleanField(default=False)
    payment_option = models.CharField(choices=PAYMENT_CHOICES, max_length=20)

    class Meta:
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return self.street_address + ',' + self.apartment_address

    def get_payment_option(self):
        return self.payment_option

    def get_street_address(self):
        return self.street_address

class Payment(models.Model):
    paymentId = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.CharField(max_length=100)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    
    
    

    def __str__(self):
        return str(self.paymentId)

    def get_id(user):
        return user.paymentId



class Contact(models.Model):
    name = models.CharField(max_length=150)
    numero = models.IntegerField()
    message=models.TextField(blank=True, null=True)


    def __str__(self):
        return self.name

base/forms.py
from django import forms
from django_countries.widgets import CountrySelectWidget
from django_countries.fields import CountryField
from .models import Profile,Contact
from django.contrib.auth.models import User

PAYMENT_CHOICES = (
    ('FLOOZ', 'FLOOZ'),
    ('TMONEY', 'TMONEY'),
)



class AddressForm(forms.Form):
    street_address = forms.CharField()
    apartment_address = forms.CharField()
    # country = CountryField(blank_label="Select country").formfield(widget=CountrySelectWidget(attrs={
    #     "class": "custom-select"
    # }))
    # zip = forms.CharField(required=False)
    # save_info = forms.BooleanField(required=False)
    # use_default = forms.BooleanField(required=False)
    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect(), choices=PAYMENT_CHOICES)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('numero', 'birth_date')

class PaymentForm(forms.Form):
    numero= forms.CharField()
    amount = forms.CharField()
    
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'numero', 'message']

base/templates/base/hauts.html
<!DOCTYPE html>
{% load static %}
{% load cart_template_tags %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Friperie en ligne - Achetez des vêtements d'occasion de qualité - Hommes et Femmes</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'css/responsive.css' %}">

	
	   <!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<!-- FontAwesome -->
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>
<style>
		a.cart .cart-basket {
				font-size: .6rem;
				/* position: absolute; */
				/* top: -6px; */
				right: -5px;
				width: 15px;
				height: 15px;
				color: #fff;
				background-color: #e76021e5;
				border-radius: 50%;
			}
			

		.label {
				  color: black;
				  padding: 8px;
				}
		.warning {background-color:  #ffff80;} /* Orange */
		.danger {background-color: #f44336;} /* Red */
				
	</style>
	
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="{% url 'index' %}">
								<img src="{% static 'img/logo.png' %}" alt="">
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li ><a href="{% url 'index' %}">Accueil</a>
									
								</li>
								<li class="current-list-item"><a href="{% url 'shop' %}">Boutique</a>
									<ul class="sub-menu">
										<li  class="current-list-item"><a href="{% url 'hauts' %}">Hauts</a></li>
										<li><a href="{% url 'pantalon' %}">Pantalons</a></li>
										<li><a href="{% url 'contact' %}">t-shirt homme</a></li>
										<li><a href="{% url 'jupes' %}">Jupes</a></li>
										<li><a href="{% url 'robes' %}">Robes</a></li>
									</ul>
								</li>
								<li><a href="{% url 'contact' %}">Contact</a></li>
								<li><a href="{% url 'about' %}">A propos</a></li>
								
							
								<li class="nav-item px-3  mb-0 position-relative d-lg-flex">
									<div id="cart" class="d-none">
							
									</div>
									{% if request.user.is_authenticated %}
										<a href="{% url 'cart' %}" class="cart position-relative d-inline-flex" aria-label="View your shopping cart">
											<!-- <i class="fas fa fa-shopping-cart fa-lg"></i> --><i class="fas fa-shopping-cart"></i>
											<span class="cart-basket d-flex align-items-center justify-content-center">
												{{ request.user|cart_item_count}}
											</span>
										</a>
										<a href="{% url 'account_logout' %}">Déconnexion</a>
									{% else %}
                                                <a href="{% url 'account_login' %}">Connexion</a>
                                                <a href="{% url 'account_signup' %}">S'inscrire</a>   
                                    {% endif %}
									<a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
								</li> 
								
							</ul>
						</nav>
						<a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->
	
	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Rechercher:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search area -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Mets à jour ta garde-robe</p>
						<h1>Boutique</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- products -->
	<div class="product-section mt-150 mb-150">
		<div class="container">

			<div class="row">
                <div class="col-md-12">
                    <div class="product-filters">
                    	<ul>
							<li class="active" data-filter=".all"{% if not category %} class="selected"{% endif %}>
								tous les articles
							</li>
							{% for c in categories %}
							<li data-filter=".{{c.name}}" {% if category.slug == c.slug %}  {% endif %}>
								{{c.name}}
							</li>
							{% endfor%}  
                            
                        </ul>
						
                    </div>
                </div>
            </div>

			
					<div class="row">
                        {% for object in ma_liste %}
                            <div class="col-lg-4 col-md-6 text-center">
                                <div class="single-product-item">
                                    <div class="product-image">
                                        <a href="{% url 'detail' object.slug %}"><img src="{{object.image.url}}" alt=""></a>
                                    </div>
                                    <a class="h6 text-decoration-Red text-truncate" href="{% url 'detail' object.slug %}">{{object.title}}-<strong>{{object.get_size_display}}</strong></a>
                                    
                                    {% comment %} <p class="product-price"> {{object.price}} cfa</p> {% endcomment %}
									{% if object.discount_price %}
										<p>
											<span>
												<h3>{{object.discount_price}} FCFA </h3>
											</span>
											<h6 class="text-muted ml-2"><del>{{object.price}} FCFA</del></h6>
										</p>
									{% else %}
									<p class="single-product-pricing"><span>{{object.price}} cfa</span> </p>    
									{% endif %}
                                    {% if object.labels == "NA" %}
                                        <a href="{{object.get_add_to_cart_url}}" class="cart-btn"><i class="fas fa-shopping-cart"></i> Acheter</a>
                                    {% else %}
                                        <div class="product-action">
                                               <span class="label danger">{{object.get_labels_display}}</span>
                                       </div>
                                   {% endif %}
                                   
                                </div>
                            </div>
                        {% endfor %}
                        
                        </div>
                        
				

			<div class="row">
				<div class="col-lg-12 text-center">
					<div class="pagination-wrap">
						<ul>
							<li><a href="{% url 'hauts' %}">Precedent</a></li>
							
							<li><a class="active" href="{% url 'hauts' %}">Suivant</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end products -->

	
<!-- footer -->
<div class="footer-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="footer-box about-widget">
					<h2 class="widget-title">A propos de nous</h2>
					<p>ReStyle est une société nouvellement au Togo, spécialisée dans la vente de friperies (abloni) de première qualité.</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box get-in-touch">
					<h2 class="widget-title">Nous contacter</h2>
					<ul>
						<li>Lomé,Togo.</li>
						<li>akomlassan26@gmail.com</li>
						<li>+228 92-38-35-69</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box pages">
					<h2 class="widget-title">Pages</h2>
					<ul>
						<li><a href="{% url 'index' %}">Home</a></li>
						<li><a href="{% url 'about' %}">About</a></li>
						<li><a href="{% url 'shop' %}">Shop</a></li>
						<li><a href="{% url 'contact' %}">Contact</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="footer-box subscribe">
					<h2 class="widget-title">S'inscrire</h2>
					<p>Recevez des messages directement sur votre portable dès qu'il y'a de nouveaux articles.</p>
					<form action="index.html">
						<input type="email" placeholder="Email">
						<button type="submit"><i class="fas fa-paper-plane"></i></button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end footer -->
	
	
	
	<!-- jquery -->
	<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>